version: '3'

services:
  web:
    build: .
    container_name: uptrader_web
    command: sh entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: uptrader_db
    ports:
      - "5432:5432"
    volumes:
      - uptrader_db_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  uptrader_db_data:
